### ISSUE TITLE
Revisão - Criando um componente básico com ReactJs

### ISSUE THREAD

**Issue by paulovictordev** [reactjs-ceara/javascript-exercises#1]
Fala pessoal! Como estão? Depois de um tempo retomei os estudos na stack JavaScript.

Estou disponibilizando para revisão o codigo da minha tarefa aqui [ReactJS - CodeSandBoxe](https://codesandbox.io/s/reactjs-basico-kcsd9) 

Qualquer observação será bem recebida. @cicerohen @mensonones  .

**Comment by cicerohen** [comment]
@paulovictordev veja como ficaria usando hooks praquele pequeno trecho do estado. :)

**Comment by cicerohen** [comment]
@paulovictordev crie mais um ou dois componentes que tenham algum estado e experimente usar Context pra compartilhar o estado entre eles. :)

**Comment by paulovictordev** [comment]
Certo @cicerohen , vou desenrolar aqui.

**Comment by paulovictordev** [comment]
@cicerohen , depois de lê algumas coisa e entender os conceitos básicos, eu criei alguns componentes pra  fazer uma lista de convidados. [CodeSandBox](https://yhypy.csb.app/) 
Eu gostei do resultado.
